name: Release     #Наименования текущего workflow

on:                     #Секция условий выполнения текущего workflow
  workflow_run: #Условия запуска текущего workflow
    workflows: ["Pre-commit"] #Workflow, который запускается первым 
    branches: [master]          #Ветка, в которой запускается первый workflow
    types:                    #Тип результата выполнения первого workflow
      - completed             #Триггер статуса выполнения первого workflow
  workflow_dispatch:          #Условия запуска текущего workflow 
  push: 
    branches:
      - master
      - beta
    #paths:
    #  - '**/*.tpl'
    #  - '**/*.tf'
    #  - '.github/workflows/release.yml'

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
          contents: write       # to be able to publish a GitHub release
          pull-requests: write  # to be able to comment on released pull requests
          issues: write         # to be able to comment on released issues
        #  Skip running release workflow on forks
        if: github.repository_owner == 'lugovskovp'
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false
            fetch-depth: 0
    
        - name: Release
          uses: cycjimmy/semantic-release-action@v4
          with:
            semantic_version: 24
            #@semantic-release/exec
            extra_plugins: |
                @semantic-release/changelog@v6
                @semantic-release/git@v10
                conventional-changelog-eslint@3.0.9
                conventional-changelog-conventionalcommits@5.0.0
                @semantic-release/exec@v7
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

